###
POST  http://localhost:3000/users
content-type: application/json

{
  "name": "usuario0",
  "email": "usuario0@f18s.f9s",
  "admin": false,
  "password": "secreto"
}

###
POST  http://localhost:3000/users
content-type: application/json

{
  "name": "usuario1",
  "email": "usuario1@f18s.f9s",
  "admin": false,
  "password": "secreto"
}

###
POST  http://localhost:3000/users
content-type: application/json

{
  "name": "admin",
  "email": "admin@f18s.f9s",
  "admin": true,
  "password": "secreto"
}

###
POST  http://localhost:3000/users
content-type: application/json

{
  "name": "Flávio Menezes dos Reis",
  "email": "flavio-reis@pge.rs.gov.br",
  "admin": true,
  "password": "secreto"
}

###
POST  http://localhost:3000/users
content-type: application/json

{
  "name": "usuario2",
  "email": "usuario2@f18s.f9s",
  "password": "secreto"
}
